# Generated by Django 4.2.4 on 2023-08-16 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filialeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filialeName', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='roleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userTable',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('filialeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.filialetable')),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.roletable')),
            ],
        ),
    ]
